# SPDX-FileCopyrightText: 2024 David Mallasén Quintana
# SPDX-License-Identifier: LGPL-3.0-or-later
# Source: https://github.com/davidmallasen/arithmetic_units

version = 1

[[annotations]]
path = [
    "requirements.txt", 
    "environment.yml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 David Mallasén Quintana"
SPDX-License-Identifier = "LGPL-3.0-or-later"
